apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patroni-cluster.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patroni-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword | quote }}
  REPLICATION_PASSWORD: {{ .Values.postgresql.replicationPassword | quote }}
  APP_DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  PATRONI_SUPERUSER_PASSWORD: {{ .Values.postgresql.postgresPassword | quote }}
  PATRONI_REPLICATION_PASSWORD: {{ .Values.postgresql.replicationPassword | quote }}
